services:
  arrange-postgres:
    image: pgvector/pgvector:pg17
    container_name: arrange-postgres
    environment:
      POSTGRES_DB: arrange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - arrange-postgres:/var/lib/postgresql/data
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d arrange" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  arrange:
    image: arrange
    container_name: arrange
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      arrange-postgres:
        condition: service_healthy
    volumes:
